name: arabize_example
description: Example app for arabize.
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.10.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
