name: arabize_cli
description: Command line tool to check, fix and translate Flutter apps for Arabic and RTL.
version: 0.0.1
repository: https://github.com/Omarelnasherty/arabize/tree/main/packages/arabize_cli
issue_tracker: https://github.com/Omarelnasherty/arabize/issues
topics:
  - arabic
  - rtl
  - localization
  - flutter

environment:
  sdk: ^3.10.0
resolution: workspace

executables:
  arabize:

dev_dependencies:
  test: ^1.25.0
